--CREATE DATABASE SirketDB

--USE SirketDB

--BÝRÝM TABLOSU BAÞLADI

CREATE TABLE Birim
(
	BirimNo INT PRIMARY KEY IDENTITY (1,1),
	BirimAD NVARCHAR(50) UNIQUE NOT NULL
)

INSERT INTO Birim VALUES ('Hukuk'),('Finans'),('Pazarlama'),('Planlama'),('Proje Yönetimi')

--BÝRÝM TABLOSU BÝTTÝ; UNVAN TABLOSU BAÞLADI

CREATE TABLE Unvan
(
	UnvanNo INT PRIMARY KEY IDENTITY (1,1),
	UnvanAD NVARCHAR(100) UNIQUE NOT NULL
)

INSERT INTO Unvan VALUES ('Mühendis'),('IK Uzmaný'),('Teknisyen'),('Mimar'),('Temizlik Görevlisi'),
('Müdür Yardýmcýsý'),('Asistan'),('Sekreter'),('Denetmen'),('Müdür')

--UNVAN TABLOSU BÝTTÝ; IL TABLOSU BAÞLADI

CREATE TABLE Il
(
	IlNo INT PRIMARY KEY IDENTITY (1,1),
	IlAD NVARCHAR(40) UNIQUE NOT NULL
)

INSERT INTO Il  VALUES ('Ankara'),('Bursa'),('Antalya'),('Eskiþehir'),('Ýstanbul'),
('Ýzmir'),('Muðla'),('Balýkesir'),('Manisa'),('Aydýn')

---IL TABLOSU BÝTTÝ; ÝLÇE TABLOSU BAÞLADI

CREATE TABLE Ilce
(
	IlceNo INT PRIMARY KEY IDENTITY (1,1),
	IlceAD NVARCHAR(40) UNIQUE NOT NULL,
	IlID INT FOREIGN KEY REFERENCES Il(IlNo) NOT NULL

)

INSERT INTO  Ilce (IlceAD,IlID) VALUES ('Polatlý',1),('MustafaKemalPaþa',2),('Manavgat',3),('Odun Pazarý',4),('Kadýköy',5),('Bornova',6),('Ortaca',7),('Edremit',8),('Soma',9),('Didim',10)

--ÝLÇE TABLOSU BÝTTÝ; PROJE TABLOSU BAÞLADI

CREATE TABLE Proje
(
	ProjeAd NVARCHAR(250) UNIQUE NOT NULL,
	BaslamaTarihi DATE NOT NULL,
	BitisTarihi DATE NOT NULL
)

INSERT INTO Proje (ProjeAd,BaslamaTarihi,BitisTarihi) VALUES
('Akýllý Þehir Ankara',GETDATE(),DATEADD(YEAR, 1, GETDATE())),
('Akýllý Þehir Bursa',GETDATE(),DATEADD(YEAR, 1, GETDATE())),
('Akýllý Þehir Ýstanbul',GETDATE(),DATEADD(YEAR, 1, GETDATE())),
('Akýllý Þehir Eskiþehir',GETDATE(),DATEADD(YEAR, 1, GETDATE())),
('Akýllý Þehir Balýkesir',GETDATE(),DATEADD(YEAR, 1, GETDATE())),
('Akýllý Þehir Muðla',GETDATE(),DATEADD(YEAR, 1, GETDATE())),
('Akýllý Þehir Aydýn',GETDATE(),DATEADD(YEAR, 1, GETDATE())),
('Akýllý Þehir Manisa',GETDATE(),DATEADD(YEAR, 1, GETDATE())),
('Akýllý Þehir Antalya',GETDATE(),DATEADD(YEAR, 1, GETDATE())),
('Akýllý Þehir Balýkesir',GETDATE(),DATEADD(YEAR, 1, GETDATE()))

CREATE TABLE Personel
(
	PersonelTC BIGINT PRIMARY KEY NOT NULL,
	PersonelAdi NVARCHAR(30) NOT NULL,
	PersonelSoyadi NVARCHAR(40) NOT NULL,
	Cinsiyet NVARCHAR(5),
	DogumTarihi DATE NOT NULL,
	/* 
	PROJE ÝÇÝN VERÝ TABANIMIZDA TUTTUÐUMUZ ÝLLERDEN BÝRÝNDE DOÐMAMIÞ OLABÝLÝR.
	BUNDAN DOLAYI BU VERÝYÝ ÝLLER TABLOSUNA BAÐLAMAYACAÐIM.
	ZATEN VERDÝÐÝNÝ DÖKÜMANDA BÖYLE BÝR ÞEY ÝSTENMÝYOR OLARAK ANLAÞILIYOR.
	ANCAK ÞÖYLE BÝR DURUM VAR.
	HER ÞEHÝR ÝÇÝN BÝR PERSONEL EKLENECEK DÝYE OLDUKÇA MUÐLÂK BÝR MADDE EKLEMÝÞSÝNÝZ.
	BU DEMEK OLUYOR KÝ PROJE TABLOSU ÝÇÝN YENÝ BÝR KOLON AÇILACAK VE ORAYA PERSONELLER ID ÝLE EKLENECEK.
	YA DA TAM DA ÝÞÝME GELDÝÐÝ GÝBÝ ANLAYARAK DOÐUM YERÝ BÝLGÝSÝNÝ ÝLLER TABLOSUNA BAÐLARIM.
	BUNDAN DOLAYI ÝKÝNCÝ YOLU SEÇEREK DOÐUM YERÝNÝ ÝLLER TABLOSUNA BAÐLAYACAÐIM.
	*/
	DogumYeri INT NOT NULL FOREIGN KEY REFERENCES Il(IlNo),
	BaslamaTarihi DATE NOT NULL,
	BirimNo INT NOT NULL FOREIGN KEY REFERENCES Birim(BirimNo),
	UnvanNo INT NOT NULL FOREIGN KEY REFERENCES Unvan(UnvanNo),
	/*
	T-SQL ÝLE ALAKALI YAPTIÐIM DÖKÜMAN ARAÞTIRMALARINDA VE OKUDUÐUM YORUMLARDA ÞUNU ÖÐRENDÝM.
	EÐER KESÝRLÝ SAYILARI SAKLAYACAKSANIZ YA DA ÝÞLEM YAPMAK ÝÇÝN KULLANACAKSANIZ,
	VE EÐER BU SAYININ BELÝRTÝÐÝ ÞEY PARA ÝSE,
	ASLA MONEY DEÐÝÞKENÝNÝ KULLANMAYIN.
	EN BERBAT DEÐÝÞKEN MONEY'DÝR
	HER ZAMAN DECIMAL KULLANIN.
	SEBEBÝNÝ BÝLMÝYORUM ANCAK T-SQL KULLANANLAR HATTA SQL KULLANANLAR HEP BÖYLE SÖYLÜYOR.
	BUNDAN DOLAYI BENDE DECÝMAL KULLANACAÐIM
	*/
	Maas DECIMAL(8,2) NOT NULL,
	Prim DECIMAL (7,2),
)

INSERT INTO Personel (PersonelTC,PersonelAdi,PersonelSoyadi,Cinsiyet,DogumTarihi,DogumYeri,BaslamaTarihi,BirimNo,UnvanNo,Maas,Prim)
VALUES 
(11111111111,'Tek','CELSEOÐLU','Erkek',DATEADD(YEAR,-30,GETDATE()),1,DATEADD(YEAR,-3,GETDATE()),1,10,50000,2000),
(11111111112,'Bal Döker','YALAROÐLU','Diðer',DATEADD(YEAR,-32,GETDATE()),2,DATEADD(YEAR,-5,GETDATE()),1,5,20000,1000),
(11111111113,'Jet','FADIL','Erkek',DATEADD(YEAR,-60,GETDATE()),3,DATEADD(YEAR,-25,GETDATE()),2,10,90000,10000),
(11111111114,'Beþer','ÇETEROÐLU','Erkek',DATEADD(YEAR,-50,GETDATE()),4,DATEADD(YEAR,-20,GETDATE()),2,6,70000,9000),
(11111111115,'Sülün','OSMAN','Erkek',DATEADD(YEAR,-80,GETDATE()),5,DATEADD(YEAR,-60,GETDATE()),3,10,60000,3000),
(11111111116,'Her Türlü','SATAROÐLU','Erkek',DATEADD(YEAR,-52,GETDATE()),6,DATEADD(YEAR,-55,GETDATE()),3,7,50000,2000),
(11111111117,'Mete','ÝÞEYARAMAZOÐLU','Erkek',DATEADD(YEAR,-40,GETDATE()),7,DATEADD(YEAR,-7,GETDATE()),4,3,40000,1000),
(11111111118,'Odtü','MÜHENDÝSÝ','Diðer',DATEADD(YEAR,-25,GETDATE()),8,DATEADD(YEAR,-1,GETDATE()),4,10,10000,500),
(11111111119,'Þehrazat','AHLAKLI','KADIN',DATEADD(YEAR,-30,GETDATE()),9,DATEADD(YEAR,-1,GETDATE()),5,10,20000,99999.99),
(11111111120,'Onur','AHLAKSIZ','Erkek',DATEADD(YEAR,-30,GETDATE()),10,DATEADD(YEAR,-5,GETDATE()),5,10,999999.99,99999.99)