//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginWFA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ActivityLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActivityLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoginWFA.ActivityLocalization", typeof(ActivityLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kütle boy indeks.
        /// </summary>
        internal static string label10 {
            get {
                return ResourceManager.GetString("label10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hedef.
        /// </summary>
        internal static string label13 {
            get {
                return ResourceManager.GetString("label13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boy.
        /// </summary>
        internal static string label3 {
            get {
                return ResourceManager.GetString("label3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilo.
        /// </summary>
        internal static string label5 {
            get {
                return ResourceManager.GetString("label5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçen haftaki ortalama kalori alımınız. Günlük şekilde..
        /// </summary>
        internal static string label6 {
            get {
                return ResourceManager.GetString("label6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metobolizma Oranın.
        /// </summary>
        internal static string label8 {
            get {
                return ResourceManager.GetString("label8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktiflik Seviyen.
        /// </summary>
        internal static string lbl1 {
            get {
                return ResourceManager.GetString("lbl1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aşağıda verilen bilgiler tarafımıza vermiş olduğunuz bilgilere göre hesaplanmıştır. Güvenilir bilgi almak için lütfen diyetisyeniniz veya doktorunuza danışınız. Bize vermiş olduğunuz bilgilere göre durumunuz aşağıdaki gibidir..
        /// </summary>
        internal static string lblSuggestion {
            get {
                return ResourceManager.GetString("lblSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aşağıda verilen bilgiler tarafımıza vermiş olduğunuz bilgilere göre hesaplanmıştır. Güvenilir bilgi almak için lütfen diyetisyeniniz veya doktorunuza danışınız. Bize vermiş olduğunuz bilgilere göre durumunuz aşağıdaki gibidir..
        /// </summary>
        internal static string lblWeightStatus {
            get {
                return ResourceManager.GetString("lblWeightStatus", resourceCulture);
            }
        }
    }
}
