//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginWFA {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SummaryLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SummaryLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LoginWFA.SummaryLocalization", typeof(SummaryLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEMEK SİL.
        /// </summary>
        internal static string btnDeleteFood {
            get {
                return ResourceManager.GetString("btnDeleteFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞÜN SİL.
        /// </summary>
        internal static string btnDeleteMeal {
            get {
                return ResourceManager.GetString("btnDeleteMeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞÜNLER :.
        /// </summary>
        internal static string label1 {
            get {
                return ResourceManager.GetString("label1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Günlük bazda ortalama kalori.
        /// </summary>
        internal static string label10 {
            get {
                return ResourceManager.GetString("label10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞÜN DETAYI :.
        /// </summary>
        internal static string label11 {
            get {
                return ResourceManager.GetString("label11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hedef.
        /// </summary>
        internal static string label13 {
            get {
                return ResourceManager.GetString("label13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASEL METOBOLİZMA ORTALAMASI.
        /// </summary>
        internal static string label2 {
            get {
                return ResourceManager.GetString("label2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to METOBOLİK ORTALAMA.
        /// </summary>
        internal static string label4 {
            get {
                return ResourceManager.GetString("label4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diyet.
        /// </summary>
        internal static string label9 {
            get {
                return ResourceManager.GetString("label9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aylık Ort:.
        /// </summary>
        internal static string lbl {
            get {
                return ResourceManager.GetString("lbl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞÜNLER :.
        /// </summary>
        internal static string lblLastMeals {
            get {
                return ResourceManager.GetString("lblLastMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞÜN.
        /// </summary>
        internal static string lblMeals {
            get {
                return ResourceManager.GetString("lblMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bugün:.
        /// </summary>
        internal static string lblToday {
            get {
                return ResourceManager.GetString("lblToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haftalık Ort:.
        /// </summary>
        internal static string lblWeekAverage {
            get {
                return ResourceManager.GetString("lblWeekAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEPSİ.
        /// </summary>
        internal static string rdbAll {
            get {
                return ResourceManager.GetString("rdbAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HEPSİ.
        /// </summary>
        internal static string rdbAllMealTime {
            get {
                return ResourceManager.GetString("rdbAllMealTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAHVALTI.
        /// </summary>
        internal static string rdbBreakFast {
            get {
                return ResourceManager.GetString("rdbBreakFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AKŞAM YEMEĞİ.
        /// </summary>
        internal static string rdbDinner {
            get {
                return ResourceManager.GetString("rdbDinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUGÜN.
        /// </summary>
        internal static string rdbLastDay {
            get {
                return ResourceManager.GetString("rdbLastDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEÇEN AY.
        /// </summary>
        internal static string rdbLastMonth {
            get {
                return ResourceManager.GetString("rdbLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEÇEN HAFTA.
        /// </summary>
        internal static string rdbLastWeek {
            get {
                return ResourceManager.GetString("rdbLastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ÖĞLEN YEMEĞİ.
        /// </summary>
        internal static string rdbLunch {
            get {
                return ResourceManager.GetString("rdbLunch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATIŞTIRMALIK.
        /// </summary>
        internal static string rdbSnack {
            get {
                return ResourceManager.GetString("rdbSnack", resourceCulture);
            }
        }
    }
}
